<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abu Zer | Error Types | </title>
    <link rel="icon" type="image/x-icon" href="IT ADMIN-Abu.jpeg">
    <link rel="stylesheet" href="styles/new.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>
<body>
    <div class="container">
        <h1>Syntax, Logical, and Runtime Errors</h1>
        <article>
            By the end of this reading, you'll be able to:
            <ul>
                <li>Recognize common types of errors in JavaScript</li>
            </ul>
            Here are some of the most common errors in JavaScript:
            <ul>
                <li>ReferenceError</li>
                <li>SyntaxError</li>
                <li>TypeError</li>
                <li>RangeError</li>
            </ul>
            There are some other errors in JavaScript. These other errors include:
            <ul>
                <li>AggregateError</li>
                <li>Error</li>
                <li>InternalError</li>
                <li>URIError</li>
            </ul>
            However, in this reading, I'll focus on the Reference, Syntax, Type, and Range errors.
        </article>
        <strong>Note: Please copy the code and run it in the console to see the output</strong>
      
      <br>  <code>
            <pre>
console.log(username);
            </pre>
        </code>
        <br>
        <strong>If the variable named username hasn't been declared, the above line of code will result in the following output:</strong>
      
      <br>  <code>
            <pre>
Uncaught ReferenceError: username is not defined
            </pre>
        </code>
        <h3>SyntaxError</h3>
        <strong>Any kind of invalid JavaScript code will cause a SyntaxError.</strong>
         
        <code>
            <pre>
var a = "there's no assignment operator here"; <br>
The above line of code will throw the following error:<br>
<blockquote>Uncaught SyntaxError: Unexpected string</blockquote>
            </pre>
        </code>
        <strong>Note: - There's an interesting caveat regarding the SyntaxError in JavaScript: it cannot be caught using the try-catch block.</strong>
        <h3>TypeError</h3>
        <p>A TypeError is thrown when, for example, trying to run a method on a non-supported data type.</p>
         <br>
        <code>
            <pre>
"hello".pop() // Uncaught TypeError: "hello".pop is not a function
            </pre>
        </code>
        <h3>RangeError</h3>
        <p>A RangeError is thrown when we're giving a value to a function, but that value is out of the allowed range of acceptable input values.</p>
        <p>Here's a simple example of converting an everyday Base 10 number (a number of the common decimal system) to a Base 2 number (i.e., binary number).</p>
        <br>
        <code>
            <pre>
(10).toString(2); // '1010'
            </pre>
        </code> <br>
        <p>The value of 2 when passed to the toString() method is like saying to JavaScript: "convert the value of 10 of the Base 10 number system to its counterpart in the Base 2 number system".</p>
        <p>JavaScript obliges and "translates" the "regular" number 10 to its binary counterpart.</p>
        <p>Besides using Base 2 number systems, I can also use Base 8, like this:</p>
        <code>
            <pre>
(10).toString(8); // 12
            </pre>
        </code>
        <br>
        <p>I get back the value 12, which is the plain number 10, written in the Base 8 number system.</p>
        <p>However, if I try to use a non-existing number system, such as an imaginary Base 100, since this number system effectively doesn't exist in JavaScript, I will get the RangeError because a non-existing Base 100 system is <b>out of range</b> of the number systems that are available to the toString() method:</p>
        <code>
            <pre>
(10).toString(100); // Uncaught RangeError: toString() radix argument must be between 2 and 36
            </pre>
        </code>

    <div>
        <h3>Exercise: Error Prevention</h3>
        <p>Instructions</p>
        <ul>
            <li>
                Task 1: Code a function declaration<br>
                You need to code a function declaration named addTwoNums, which accepts numbers a and b and console logs a + b.
            </li>
            <li>
                Task 2: Invoke the addTwoNums function with a number and a string<br>
                You need to invoke the addTwoNums using the following arguments: 5 and "5".
            </li>
            <li>
                Task 3: Update the addTwoNums function with a try...catch block<br>
                Add the try and catch blocks inside the function definition's body. For now, just make sure that the console log of a + b is inside the try block. Additionally, the catch block should catch an error named err and, inside the body of the catch block, you need to console log the err value.
            </li>
            <li>
                Task 4: If the passed-in arguments are not numbers, throw an error<br>
                If either of the arguments passed to the addTwoNums are not numbers, you'll throw an error.<br>
                Specifically, code a conditional with the following logic:<br>
                <ul>
                    <li>
                        if the typeof the a parameter is not equal to 'number', throw a new ReferenceError. Inside the ReferenceError, pass a custom error message of 'the first argument is not a number'.
                    </li>
                    <li>
                        else if the typeof the b parameter is not equal to 'number', throw a new ReferenceError. Inside the ReferenceError, pass a custom error message of 'the second argument is not a number'.
                    </li>
                    <li>
                        else, console log a + b
                    </li>
                </ul>
                Once you've completed this task, all the code inside the try block will be inside these conditional statements.
            </li>
            <li>
                Task 5: Update the catch block<br>
                Inside the catch block, update the code from console.log(err) to console.log("Error!", err).
            </li>
            <li>
                Task 6: Invoke the addTwoNums function<br>
                Invoke the addTwoNums function using 5 and "5" as arguments.
            </li>
            <li>
                Task 7: Add another console log under the addTwoNums function invocation<br>
                Add another line of code that console logs the string "It still works".
            </li>
        </ul>
        <h3>
            Solution: Error prevention
        </h3>
        <blockquote> To test this run the code in Console of the browser</blockquote>
        <code>
            <pre>
                function addTwoNums(a,b) {
                    try {
                        if(typeof(a) != 'number') {
                            throw new ReferenceError('the first argument is not a number')
                        } else if (typeof(b) != 'number') {
                            throw new ReferenceError('the second argument is not a number')
                        } else {
                            console.log(a + b)
                        }
                    } catch(err) {
                        console.log("Error!", err)
                    }
                }
                addTwoNums(5, "5")
                console.log("It still works")
            </pre>
        </code>
    </div>
    </div>
</body>
</html>
